import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from 'react'

const Home = ({ products }) => {
  const [produtos, setProducts] = useState(products)
  const [page, setPage] = useState(1)

  const nextProducts = async() => {
    setPage(page+1)
  }

  useEffect( async() => {
    const response = await fetch(`https://frontend-intern-challenge-api.iurykrieger.vercel.app/products?page=${page}`)
    const data = await response.json()

    setProducts(data.products)
  }, [page])

  const previousProducts = async() => {
    setPage(page-1)
  }

  useEffect( async() => {
    const response = await fetch(`https://frontend-intern-challenge-api.iurykrieger.vercel.app/products?page=${page}`)
    const data = await response.json()

    setProducts(data.products)
  }, [page])

  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1>Tech Shop</h1>
        <h2>A sua loja online de Eletrônicos</h2>
      </header>

      <main className={styles.main}>

        <div className={styles.productList}>
          {produtos.map((produto) => (
            <div key={produto.id} className={styles.productItem}>
              <img src={produto.image} width={160} height={160} />
              <h3>{produto.name}</h3>
              <p>{produto.description}</p>
              <p>De: R${produto.oldPrice}</p>
              <h4>Por: R${produto.price}</h4>
              <p>Ou {produto.installments.count}x de R${produto.installments.value}</p>
            </div>
          ))}
        </div>

        <div className={styles.navButtons}>

          <button type="button" className={styles.btnCarregarMaisProdutos} onClick={previousProducts}>
            Página anterior
          </button>
          <button type="button" className={styles.btnCarregarMaisProdutos} onClick={nextProducts}>
            Próxima página
          </button>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps = async() => {
  const response = await fetch('https://frontend-intern-challenge-api.iurykrieger.vercel.app/products?page=1')
  const data = await response.json()

  return {
    props: {
      products: data.products
    }
  }
}

export default Home
