import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from 'react'
import ProductList from '../components/ProductList'

const Home = ({ products }) => {
  const [produtos, setProducts] = useState(products)
  const [page, setPage] = useState(1)

  const nextProducts = async() => {
    setPage(page+1)
  }

  useEffect(async() => {
    const response = await fetch(`https://frontend-intern-challenge-api.iurykrieger.vercel.app/products?page=${page}`)
    const data = await response.json()

    setProducts(data.products)

    if (page > 1)
      document.getElementById('previousBtn').hidden = false
    else
      document.getElementById('previousBtn').hidden = true
  }, [page])

  const previousProducts = async() => {
    setPage(page-1)
  }

  useEffect(async() => {
    const response = await fetch(`https://frontend-intern-challenge-api.iurykrieger.vercel.app/products?page=${page}`)
    const data = await response.json()

    setProducts(data.products)
    if (page > 1)
      document.getElementById('previousBtn').hidden = false
    else
      document.getElementById('previousBtn').hidden = true
  }, [page])

  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1>Tech Shop</h1>
        <h2>A sua loja online de Eletrônicos</h2>
      </header>

      <main className={styles.main}>

        <ProductList produtos={produtos} />

        <div className={styles.navButtons}>

          <button type="button" id="previousBtn" className={styles.btnCarregarMaisProdutos} onClick={previousProducts}>
            Página anterior
          </button>
          <button type="button" className={styles.btnCarregarMaisProdutos} onClick={nextProducts}>
            Próxima página
          </button>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps = async() => {
  const response = await fetch('https://frontend-intern-challenge-api.iurykrieger.vercel.app/products?page=1')
  const data = await response.json()

  return {
    props: {
      products: data.products
    }
  }
}

export default Home
